name: Build and push docker image to ACR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:

  artifact:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/cicd-dev/cicd-image-repo:${{ steps.sha.outputs.sha_short }} .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/cicd-dev/cicd-image-repo:${{ steps.sha.outputs.sha_short }}
